export const STOP_WORDS = new Set([
    "a", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any", "are", "aren't", "as", "at",
  "be", "because", "been", "before", "being", "below", "between", "both", "but", "by",
  "can", "cannot", "could", "couldn't", "did", "didn't", "do", "does", "doesn't", "doing", "don't", "down", "during",
  "each", "few", "for", "from", "further", "had", "hadn't", "has", "hasn't", "have", "haven't", "having", "he", "he'd", "he'll", "he's", "her", "here", "here's", "hers", "herself", "him", "himself", "his", "how", "how's",
  "i", "i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "isn't", "it", "it's", "its", "itself",
  "let's", "me", "more", "most", "mustn't", "my", "myself",
  "no", "nor", "not", "of", "off", "on", "once", "only", "or", "other", "ought", "our", "ours", "ourselves", "out", "over", "own",
  "same", "shan't", "she", "she'd", "she'll", "she's", "should", "shouldn't", "so", "some", "such",
  "than", "that", "that's", "the", "their", "theirs", "them", "themselves", "then", "there", "there's", "these", "they", "they'd", "they'll", "they're", "they've", "this", "those", "through", "to", "too",
  "under", "until", "up", "very",
  "was", "wasn't", "we", "we'd", "we'll", "we're", "we've", "were", "weren't", "what", "what's", "when", "when's", "where", "where's", "which", "while", "who", "who's", "whom", "why", "why's", "with", "won't", "would", "wouldn't",
  "you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself", "yourselves",

  // Corporate / Resume Filler Words (The Fix)
  "experience", "years", "work", "team", "role", "candidate", "skills", "ability", "working", 
  "knowledge", "strong", "preferred", "qualifications", "degree", "looking", "will", "must", 
  "requirements", "responsibilities", "collaborate", "develop", "implement", "maintain", 
  "ensure", "provide", "providing", "support", "participate", "assist", "help", "drive", 
  "environment", "excellent", "proven", "familiarity", "proficiency", "proficient", 
  "understanding", "good", "plus", "like", "using", "used", "various", "building", "build",
  "create", "creating", "issues", "complex", "solutions", "best", "practices", "projects",
  "seamless", "optimal", "overall", "clean", "efficient", "maintainable", "tailored", 
  "application", "applications", "functionality", "product", "platform", "services", "system",
  "technologies", "technology", "stay", "updated", "trends", "fields", "ideas", "success",
  "business", "engagement", "troubleshoot", "debug", "integration", "integrations", "integrating",
  "collaboration", "communication", "effectively", "box", "challenges", "emerging", "passion",
  "contributing", "cutting-edge", "leveraging", "review", "reviews", "constructive", "feedback",
  "enhance", "user", "experience", "part", "including", "particularly", "related", "enabled",
  "wide", "range", "stakeholders", "across", "multiple", "departments", "fast-paced",
  "prioritize", "managing", "management", "competing", "deadlines", "adapting", "changing",
  "environments", "self-motivated", "self-starter", "initiative", "innovative", "creativity",
  "creative", "critical", "thinking", "analytical", "detail-oriented", "organized",
    "multitask", "multitasking", "time", "efficiently", "efficient", "lead", "leadership",
    "mentorship", "mentoring", "coaching", "guidance", "motivated", "driven",
    
  // ==============================================================================
  // 1. STANDARD ENGLISH (Pronouns, Prepositions, Conjunctions, Basic Verbs)
  // ==============================================================================
  "a", "about", "above", "across", "after", "afterwards", "again", "against", "all",
  "almost", "alone", "along", "already", "also", "although", "always", "am", "among",
  "amongst", "amoungst", "amount", "an", "and", "another", "any", "anyhow", "anyone",
  "anything", "anyway", "anywhere", "are", "aren't", "around", "as", "at",
  "back", "be", "became", "because", "become", "becomes", "becoming", "been", "before",
  "beforehand", "behind", "being", "below", "beside", "besides", "between", "beyond",
  "bill", "both", "bottom", "but", "by",
  "call", "can", "cannot", "cant", "co", "con", "could", "couldn't", "couldnt", "cry",
  "de", "describe", "detail", "did", "didn't", "do", "does", "doesn't", "doing",
  "don't", "done", "down", "due", "during",
  "each", "eg", "eight", "either", "eleven", "else", "elsewhere", "empty", "enough",
  "etc", "etcetera", "even", "ever", "every", "everyone", "everything", "everywhere",
  "except",
  "few", "fifteen", "fify", "fill", "find", "fire", "first", "five", "for", "former",
  "formerly", "forty", "found", "four", "from", "front", "full", "further",
  "get", "give", "go",
  "had", "hadn't", "has", "hasn't", "hasnt", "have", "haven't", "having", "he",
  "he'd", "he'll", "he's", "hence", "her", "here", "here's", "hereafter", "hereby",
  "herein", "hereupon", "hers", "herself", "him", "himself", "his", "how", "how's",
  "however", "hundred",
  "i", "i'd", "i'll", "i'm", "i've", "ie", "if", "in", "inc", "indeed", "interest",
  "into", "is", "isn't", "it", "it's", "its", "itself",
  "keep",
  "last", "latter", "latterly", "least", "less", "let's", "ltd",
  "made", "many", "may", "me", "meanwhile", "might", "mill", "mine", "more",
  "moreover", "most", "mostly", "move", "much", "must", "mustn't", "my", "myself",
  "name", "namely", "neither", "never", "nevertheless", "next", "nine", "no",
  "nobody", "none", "noone", "nor", "not", "nothing", "now", "nowhere",
  "of", "off", "often", "on", "once", "one", "only", "onto", "or", "other",
  "others", "otherwise", "ought", "our", "ours", "ourselves", "out", "over", "own",
  "part", "per", "perhaps", "please", "put",
  "rather", "re",
  "same", "see", "seem", "seemed", "seeming", "seems", "serious", "several",
  "shan't", "she", "she'd", "she'll", "she's", "should", "shouldn't", "show",
  "side", "since", "sincere", "six", "sixty", "so", "some", "somehow", "someone",
  "something", "sometime", "sometimes", "somewhere", "still", "such", "system",
  "take", "ten", "than", "that", "that's", "the", "their", "theirs", "them",
  "themselves", "then", "thence", "there", "there's", "thereafter", "thereby",
  "therefore", "therein", "thereupon", "these", "they", "they'd", "they'll",
  "they're", "they've", "thick", "thin", "third", "this", "those", "though",
  "three", "through", "throughout", "thru", "thus", "to", "together", "too", "top",
  "toward", "towards", "twelve", "twenty", "two",
  "un", "under", "until", "up", "upon", "us",
  "very", "via",
  "was", "wasn't", "we", "we'd", "we'll", "we're", "we've", "well", "were",
  "weren't", "what", "what's", "whatever", "when", "when's", "whence", "whenever",
  "where", "where's", "whereafter", "whereas", "whereby", "wherein", "whereupon",
  "wherever", "whether", "which", "while", "whither", "who", "who's", "whoever",
  "whole", "whom", "whose", "why", "why's", "will", "with", "within", "without",
  "won't", "would", "wouldn't",
  "yet", "you", "you'd", "you'll", "you're", "you've", "your", "yours", "yourself",
  "yourselves",

  // ==============================================================================
  // 2. GENERIC JD VERBS, ACTIONS & RESPONSIBILITY (Noise in skill extraction)
  // ==============================================================================
  "ability", "able", "accept", "accomplish", "accountable", "achieve", "act",
  "action", "adapt", "add", "administer", "advocate", "align", "allow", "analyze",
  "apply", "approach", "appropriate", "assist", "assisting", "assure", "attain",
  "attend", "augment", "author",
  "balance", "based", "believe", "benefit", "bring", "build", "building",
  "calculate", "capacity", "carry", "champion", "change", "check", "choose",
  "clarify", "collaborate", "collaborating", "collaboration", "collect", "combine",
  "communicate", "communicating", "communication", "complete", "comply", "compose",
  "conduct", "connect", "consider", "construct", "consult", "contribute", "convert",
  "coordinate", "coordinating", "create", "creating", "cultivate",
  "define", "delegate", "deliver", "delivering", "demonstrate", "deploy", "derive",
  "design", "designing", "detect", "determine", "develop", "developing", "development",
  "devise", "direct", "discover", "discuss", "display", "distribute", "document",
  "draft", "drive", "duties",
  "earn", "edit", "educate", "effect", "elaborate", "elevate", "eliminate",
  "employ", "empower", "enable", "encourage", "engage", "engineer", "enhance",
  "ensure", "ensuring", "establish", "estimate", "evaluate", "examine", "execute",
  "executing", "execution", "exercise", "expand", "expect", "expected", "expects",
  "experience", "experienced", "experiment", "explain", "explore",
  "facilitate", "finalize", "focus", "follow", "forecast", "formulate", "foster",
  "fulfill", "function", "functional",
  "gain", "gather", "generate", "guide",
  "handle", "handling", "help",
  "identify", "illustrate", "implement", "implementation", "implementing", "improve",
  "improving", "include", "includes", "including", "incorporate", "increase",
  "influence", "inform", "initiate", "innovate", "inspect", "inspire", "install",
  "integrate", "interact", "interpret", "interview", "introduce", "investigate",
  "involve",
  "join", "judge", "justify",
  "know", "knowledge",
  "launch", "lead", "leadership", "learn", "leverage", "liaise", "listen", "locate",
  "maintain", "maintaining", "maintenance", "make", "manage", "management",
  "manager", "managing", "manipulate", "maximize", "measure", "meet", "mentor",
  "migrate", "minimize", "model", "modify", "monitor", "monitoring", "motivate",
  "navigate", "negotiate", "network",
  "observe", "obtain", "operate", "optimize", "optimizing", "orchestrate",
  "organize", "organized", "orient", "originate", "outline", "oversee",
  "overseeing", "own", "owning", "ownership",
  "participate", "partner", "partnering", "partners", "perform", "persuade",
  "plan", "play", "prepare", "present", "preserve", "prioritize", "process",
  "produce", "promote", "propose", "protect", "prove", "provide", "publish",
  "purchase", "pursue",
  "qualify", "quantify", "question",
  "raise", "reach", "read", "realize", "receive", "recognize", "recommend",
  "reconcile", "record", "recruit", "reduce", "refine", "reflect", "regard",
  "regulate", "reinforce", "relate", "release", "remain", "remodel", "render",
  "renew", "repair", "report", "represent", "request", "require", "required",
  "requirements", "research", "resolve", "respond", "responsible", "responsibility",
  "responsibilities", "restore", "restructure", "result", "retain", "retrieve",
  "review", "revise", "revitalize", "role", "run",
  "satisfy", "save", "schedule", "screen", "search", "secure", "seek", "seeking",
  "seeks", "select", "serve", "set", "shape", "share", "showcase", "simplify",
  "solve", "spearhead", "specialize", "specify", "standardize", "start",
  "stimulate", "strategize", "streamline", "strengthen", "structure", "study",
  "submit", "succeed", "suggest", "summarize", "supervise", "supply", "support",
  "supporting", "surpass", "sustain", "synthesize",
  "target", "teach", "test", "think", "thrive", "track", "train", "training",
  "transcribe", "transfer", "transform", "translate", "travel", "troubleshoot",
  "troubleshooting",
  "unify", "update", "upgrade", "uphold", "use", "utilize",
  "validate", "value", "verify", "view", "visit", "visualize", "volunteer",
  "want", "work", "worked", "working", "write",
  "yield",

  // ==============================================================================
  // 3. CORPORATE JARGON, FLUFF & BUZZWORDS
  // ==============================================================================
  "acumen", "adaptive", "adaptable", "agile", "ambitious", "analytical", "aptitude",
  "articulate", "asset", "autonomous", "award-winning",
  "bandwidth", "benchmark", "best-in-class", "best-of-breed", "big-picture",
  "blueprint", "buy-in",
  "candidate", "capability", "capabilities", "capital", "centric", "challenge",
  "challenging", "collaborative", "commitment", "committed", "competence",
  "competency", "competitive", "complex", "compliance", "concept", "confidence",
  "confidential", "consensus", "consultative", "core", "corporate", "creative",
  "critical", "cross-functional", "crossfunctional", "culture", "cultural",
  "cutting-edge",
  "data-driven", "deadline", "deadline-driven", "dedicated", "dedication", "deep",
  "delieverables", "department", "dependable", "detail-oriented", "detailoriented",
  "diverse", "diversity", "driven", "dynamic",
  "ecosystem", "efficiency", "efficient", "effort", "empowerment", "energetic",
  "enterprise", "enthusiastic", "entrepreneurial", "environment", "ethics",
  "excellence", "excellent", "exceptional", "exciting", "expert", "expertise",
  "exposure",
  "fast-paced", "fastpaced", "feedback", "flexibility", "flexible", "fluent",
  "framework",
  "gap", "global", "goal", "goal-oriented", "good", "granular", "great", "growth",
  "guidance",
  "hands-on", "hands-on-experience", "hardworking", "high-impact", "high-level",
  "high-performing", "highperformance", "high-quality", "highly", "holistic",
  "ideal", "impact", "impactful", "incentive", "incubate", "individual",
  "industry", "industry-leading", "initiative", "innovative", "innovation",
  "insight", "integrity", "intelligent", "interpersonal", "iterative",
  "key",
  "landscape", "leading", "lean", "legacy", "level", "lifecycle", "looking",
  "matrix", "meaningful", "methodology", "metric", "milestone", "mindset",
  "mission", "mission-critical", "mission-driven", "motivated", "multitask",
  "necessary", "needed", "next-generation", "nice-to-have", "niche",
  "objective", "opportunity", "outcome", "outstanding",
  "paradigm", "passion", "passionate", "people", "performance", "perspective",
  "phase", "pipeline", "pivot", "platform", "player", "plus", "portfolio",
  "positive", "potential", "practice", "prerequisite", "proactive", "problem",
  "problem-solver", "problemsolving", "productivity", "professional",
  "proficiency", "proficient", "profit", "program", "project", "proprietary",
  "protocol", "proven", "purpose",
  "quality", "quickly",
  "rapid", "rapidly", "related", "relationship", "relationships", "relevant",
  "reliable", "remote", "resource", "resourceful", "respect", "result-oriented",
  "results", "results-driven", "roadmap", "robust",
  "scalability", "scalable", "scale", "scenario", "scope", "seamless", "seasoned",
  "sector", "segment", "self-motivated", "self-starter", "service", "skill",
  "skilled", "skills", "skillset", "solution", "solutions", "sound", "specialist",
  "stakeholder", "stakeholders", "standard", "standards", "state-of-the-art",
  "strategic", "strategy", "strong", "style", "subject", "success", "successful",
  "suitable", "superb", "superior", "synergy",
  "tactical", "talent", "task", "tasks", "team", "team-player", "team-oriented",
  "teamwork", "technical", "technique", "technology", "thought", "tier", "tool",
  "tools", "top-tier", "traction", "traditional", "transformation", "transparency",
  "trend", "trust",
  "understanding", "unique", "unit", "urgency", "user", "user-focused",
  "value-add", "values", "variety", "various", "vendor", "venture", "verbally",
  "versatile", "vertical", "viable", "vision",
  "win-win", "wisdom", "workflow", "workforce", "world-class",

  // ==============================================================================
  // 4. HIRING, HR, BENEFITS, EDUCATION & EEO BOILERPLATE
  // ==============================================================================
  "401k",
  "accommodation", "affirmative", "age", "ancestry", "applicant", "applicants",
  "application", "apply", "applying", "assignments",
  "background", "bachelor", "bachelors", "basis", "benefits", "bonus", "business",
  "career", "certification", "certifications", "citizen", "citizenship", "color",
  "commensurate", "commission", "company", "compensation", "condition", "contract",
  "corporation", "course", "courses", "creed", "criminal", "cv",
  "degree", "dental", "diploma", "disability", "discipline", "discriminate",
  "discrimination", "division", "doctorate", "drug-free",
  "education", "educational", "eligibility", "eligible", "employee", "employer",
  "employment", "equal", "equity", "equivalent", "ethnicity", "expression",
  "federal", "female", "firm", "full-time", "fulltime",
  "ged", "gender", "genetic", "graduate", "group",
  "hiring", "history", "holiday", "hr", "human",
  "identity", "immigration", "inclusion", "inclusive", "insurance", "intern",
  "internship", "interview",
  "job",
  "law", "leave", "legal", "location",
  "male", "mandatory", "marital", "master", "masters", "medical", "mental",
  "military", "minority", "miscellaneous",
  "national", "nationality", "offer", "office", "onboarding", "onsite", "opening",
  "option", "orientation", "origin", "overtime",
  "package", "paid", "part-time", "parttime", "pay", "payroll", "permanent", "phd",
  "physical", "policy", "position", "posting", "pregnancy", "preferred",
  "procedure", "profile", "protected", "pto",
  "qualification", "qualifications", "qualified",
  "race", "recruiter", "recruitment", "recruiting", "religion", "relocation",
  "remotely", "resume", "retirement",
  "salary", "screening", "selection", "sex", "sexual", "shortlisted", "sponsorship",
  "staff", "staffing", "startup", "status", "stock", "submission",
  "temporary", "term", "title", "tuition",
  "undergraduate", "union",
  "vacation", "vacancy", "vaccine", "veteran", "visa", "wfh", "workplace",

  // ==============================================================================
  // 5. TIME, FREQUENCY & NUMERICAL REFERENCES
  // ==============================================================================
  "1st", "2nd", "3rd", "4th",
  "annual", "annually",
  "daily", "date", "day", "days", "decade", "duration",
  "early", "end", "evening",
  "fortnight", "frequency", "friday", "future",
  "hour", "hourly", "hours",
  "immediate", "immediately",
  "late", "long-term",
  "monday", "month", "monthly", "months", "morning",
  "night", "nights", "noon",
  "occasionally", "ongoing",
  "past", "period", "present",
  "quarter", "quarterly",
  "regular", "regularly", "routine",
  "saturday", "shift", "short-term", "sunday",
  "thursday", "time", "timeline", "today", "tomorrow", "tuesday",
  "week", "weekday", "weekend", "weekly", "weeks", "wednesday",
  "year", "yearly", "years", "yesterday",
  "zone"
]);